import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b6c4fc',
        'outline': '#757680',
        'on-tertiary-container': '#838991',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'on-tertiary-fixed': '#161c22',
        'tertiary-fixed': '#dde3eb',
        'on-tertiary': '#ffffff',
        'primary': '#000827',
        'surface': '#f7f9fb',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#41474e',
        'on-secondary-fixed': '#111c2c',
        'on-primary-fixed-variant': '#364574',
        'surface-tint': '#4e5c8d',
        'on-primary': '#ffffff',
        'secondary-fixed': '#d8e3fa',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed-variant': '#3c475a',
        'on-surface-variant': '#45464f',
        'on-primary-container': '#7887bb',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-bright': '#f7f9fb',
        'outline-variant': '#c6c6d0',
        'on-secondary': '#ffffff',
        'tertiary': '#060b11',
        'primary-container': '#0d1e4c',
        'secondary': '#545f72',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#bcc7dd',
        'secondary-container': '#d5e0f7',
        'inverse-primary': '#b6c4fc',
        'surface-container-highest': '#e0e3e5',
        'on-secondary-container': '#586377',
        'surface-variant': '#e0e3e5',
        'on-primary-fixed': '#061846',
        'tertiary-fixed-dim': '#c1c7cf',
        'error-container': '#ffdad6',
        'primary-fixed': '#dbe1ff',
        'tertiary-container': '#1c2228',
        'surface-container': '#eceef0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        'max-width': '1200px',
        'gutter': '16px',
        'unit': '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-bold': ['Inter'],
        'body-lg': ['Inter'],
        'mono-sm': ['JetBrains Mono'],
        'headline-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'mono-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
